import java.io.File;
import java.io.FileReader;
import java.sql.*;
import java.util.Properties;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class addQuestions {
    //type in new questions in alphanumeric characters to add to your database of questions. A unique ID is autogenerated.
    static void add(String newQuestion) throws SQLException {
        Pattern pattern = Pattern.compile("[a-zA-Z0-9 ]+");

        String str = newQuestion;
        Matcher matcher = pattern.matcher(str);

        if (matcher.matches()) {
            try {

                //connection to database, here with localhost for test purposes
                Connection myConn = ConnectToDatabase.connectToDB();
                String query = " insert into Questions (Question)"
                        + " values (?)";
                PreparedStatement myStmt = myConn.prepareStatement(query);
                myStmt.setString(1, newQuestion);
                myStmt.execute();

                System.out.println("updated");
            } catch (Exception exc) {
                exc.printStackTrace();
            }

        }
    }

    public static void main(String[] args) throws SQLException {
        while (true) {
            try {

                Scanner scan = new Scanner(System.in);
                String s;
                s = scan.nextLine();
                add(s);
            } catch (Exception exc){
                exc.printStackTrace();
            }
        }
    }
}
